// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: create_post.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  author_id, text
) VALUES (
  $1, $2
)
RETURNING posts.id
`

type CreatePostParams struct {
	AuthorID uuid.UUID
	Text     *string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPost, arg.AuthorID, arg.Text)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
