// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: create_user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  line_id
) VALUES (
  $1::text
)
RETURNING users.id
`

func (q *Queries) CreateUser(ctx context.Context, lineID *string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, lineID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
