// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: create_post.sql

package db

import (
	"context"

	uuid "github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (
  author_id, text
) VALUES (
  $1, $2
)
RETURNING id, author_id, text, created_at, updated_at
`

type CreatePostParams struct {
	AuthorID uuid.UUID
	Text     *string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost, arg.AuthorID, arg.Text)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
