// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: create_post_reply.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPostReply = `-- name: CreatePostReply :one
INSERT INTO posts (
    author_id, reply_to_id, text
) VALUES (
    $1::uuid, $2::uuid, $3::text
)
RETURNING posts.id
`

type CreatePostReplyParams struct {
	AuthorID  uuid.UUID
	ReplyToID uuid.UUID
	Text      *string
}

func (q *Queries) CreatePostReply(ctx context.Context, arg CreatePostReplyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPostReply, arg.AuthorID, arg.ReplyToID, arg.Text)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
