// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delete_post_favorite.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deletePostFavorite = `-- name: DeletePostFavorite :exec
DELETE FROM
    post_favorites
WHERE
    user_id = $1::uuid
    AND post_id = $2::uuid
`

type DeletePostFavoriteParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) DeletePostFavorite(ctx context.Context, arg DeletePostFavoriteParams) error {
	_, err := q.db.Exec(ctx, deletePostFavorite, arg.UserID, arg.PostID)
	return err
}
