// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Post struct {
	ID        uuid.UUID
	AuthorID  uuid.UUID
	Text      *string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type PostFavorite struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID             uuid.UUID
	Name           string
	Nickname       string
	Biography      *string
	AvatarImageUrl *string
	BannerImageUrl *string
	Birthdate      pgtype.Timestamptz
	LineID         *string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type UserBlock struct {
	BlockerID  uuid.UUID
	BlockingID uuid.UUID
	CreatedAt  pgtype.Timestamptz
}

type UserFollow struct {
	FollowerID  uuid.UUID
	FollowingID uuid.UUID
	CreatedAt   pgtype.Timestamptz
}
