// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_user.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET
    name = COALESCE($1, name)::text,
    nickname = COALESCE($2, nickname)::text,
    biography = COALESCE($3, biography)::text
WHERE users.id = $4::uuid
`

type UpdateUserParams struct {
	Name      *string
	Nickname  *string
	Biography *string
	UserID    uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Name,
		arg.Nickname,
		arg.Biography,
		arg.UserID,
	)
	return err
}
