// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package commands

import (
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/sonnnnnnp/reverie/server/adapter/http/controller"
	"github.com/sonnnnnnp/reverie/server/pkg/line"
	"github.com/sonnnnnnp/reverie/server/usecase/http/authorize"
	"github.com/sonnnnnnp/reverie/server/usecase/http/call"
	"github.com/sonnnnnnp/reverie/server/usecase/http/call_timeline"
	"github.com/sonnnnnnp/reverie/server/usecase/http/gateway"
	"github.com/sonnnnnnp/reverie/server/usecase/http/post"
	"github.com/sonnnnnnp/reverie/server/usecase/http/timeline"
	"github.com/sonnnnnnp/reverie/server/usecase/http/user"
)

// Injectors from wire.go:

func Wire(pool *pgxpool.Pool) *controller.Controller {
	client := line.New()
	authorizeUsecase := authorize.New(pool, client)
	callUsecase := call.New(pool)
	callTimelineUsecase := call_timeline.New(pool)
	postUsecase := post.New(pool)
	gatewayUsecase := gateway.New()
	timelineUsecase := timeline.New(pool)
	userUsecase := user.New(pool)
	controllerController := controller.New(authorizeUsecase, callUsecase, callTimelineUsecase, postUsecase, gatewayUsecase, timelineUsecase, userUsecase)
	return controllerController
}
