// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delete_user_follow.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserFollow = `-- name: DeleteUserFollow :exec
DELETE FROM
    user_follows
WHERE
    follower_id = $1::uuid
    AND followed_id = $2::uuid
`

type DeleteUserFollowParams struct {
	FollowerID uuid.UUID `json:"follower_id"`
	FollowedID uuid.UUID `json:"followed_id"`
}

func (q *Queries) DeleteUserFollow(ctx context.Context, arg DeleteUserFollowParams) error {
	_, err := q.db.Exec(ctx, deleteUserFollow, arg.FollowerID, arg.FollowedID)
	return err
}
