// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/sonnnnnnp/sns-app/internal/adapter/controller"
	"github.com/sonnnnnnp/sns-app/internal/domain/ent"
	"github.com/sonnnnnnp/sns-app/internal/domain/repository/user"
	"github.com/sonnnnnnp/sns-app/internal/usecase/user"
)

// Injectors from wire.go:

func Init(db *ent.Client) *controller.Controller {
	userRepository := repository.NewUserRepository(db)
	userUsecase := usecase.NewUserUsecase(userRepository)
	controllerController := controller.New(userUsecase)
	return controllerController
}
