// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/sonnnnnnp/sns-app/internal/adapter/controller"
	"github.com/sonnnnnnp/sns-app/internal/domain/ent"
	"github.com/sonnnnnnp/sns-app/internal/domain/repository/post"
	"github.com/sonnnnnnp/sns-app/internal/domain/repository/user"
	"github.com/sonnnnnnp/sns-app/internal/usecase/authorize"
	"github.com/sonnnnnnp/sns-app/internal/usecase/post"
	"github.com/sonnnnnnp/sns-app/internal/usecase/timeline"
	"github.com/sonnnnnnp/sns-app/internal/usecase/user"
	"github.com/sonnnnnnp/sns-app/pkg/line"
)

// Injectors from wire.go:

func Wire(db *ent.Client) *controller.Controller {
	client := line.New()
	userRepository := user_repository.New(db)
	authorizeUsecase := authorize_usecase.New(client, userRepository)
	postRepository := post_repository.New(db)
	postUsecase := post_usecase.New(postRepository)
	timelineUsecase := timeline_usecase.New(postRepository)
	userUsecase := user_usecase.New(userRepository)
	controllerController := controller.New(authorizeUsecase, postUsecase, timelineUsecase, userUsecase)
	return controllerController
}
