// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/jackc/pgx/v5"
	"github.com/sonnnnnnp/sns-app/internal/adapter/controller"
	"github.com/sonnnnnnp/sns-app/internal/domain/post"
	"github.com/sonnnnnnp/sns-app/internal/domain/user"
	"github.com/sonnnnnnp/sns-app/internal/usecase/authorize"
	post2 "github.com/sonnnnnnp/sns-app/internal/usecase/post"
	"github.com/sonnnnnnp/sns-app/internal/usecase/stream"
	"github.com/sonnnnnnp/sns-app/internal/usecase/timeline"
	user2 "github.com/sonnnnnnp/sns-app/internal/usecase/user"
	"github.com/sonnnnnnp/sns-app/pkg/line"
)

// Injectors from wire.go:

func Wire(pgx2 *pgx.Conn) *controller.Controller {
	client := line.New()
	userRepository := user.New(pgx2)
	authorizeUsecase := authorize.New(client, userRepository)
	postRepository := post.New(pgx2)
	streamUsecase := stream.New()
	postUsecase := post2.New(postRepository, userRepository, streamUsecase)
	timelineUsecase := timeline.New(postRepository)
	userUsecase := user2.New(userRepository)
	controllerController := controller.New(authorizeUsecase, postUsecase, streamUsecase, timelineUsecase, userUsecase)
	return controllerController
}
